### ISSUE TITLE
Can't Upload Images

### ISSUE THREAD

**Issue by bzamora** [laurilehmijoki/jekyll-s3#26] opened 2013-02-20 12:22 UTC
The uploader seems to be corrupting images. I've tried .jpg and .png files.

**Comment by laurilehmijoki** [comment] 2013-02-23 08:09
Bzamora, can you specify how the uploader corrupts the images?

**Comment by bzamora** [comment] 2013-02-25 20:02
@laurilehmijoki The original image sizes are say 1.2 mb, when uploaded they end up being around 20k. All I have is a photos folder with .jpg files.

**Comment by laurilehmijoki** [comment] 2013-02-28 16:48
Unfortunately I don't know how to reproduce your problem, nor do I have any idea what could cause the error you are experiencing.

Is anybody else experiencing this kind of a problem? Could you provide me hints on how to reproduce it, so that I could try to fix the underlying issue.

**Comment by bzamora** [comment] 2013-02-28 19:16
@laurilehmijoki Sorry, I am not a Ruby developer so difficult for me to debug. What other details can I give to help? Like I said before, I have images in a folder on my site. Can someone confirm they've uploaded a folder with images w/ jekyll-s3? The problem comes up even w/ the bootstrap icon glyph image. I am on Windows 7. Thanks for any help

**Comment by laurilehmijoki** [comment] 2013-03-01 14:23
I've successfully uploaded images with `jekyll-s3`.

I don't know if `jekyll-s3` works on Windows. I have never tried.

Has someone used `jekyll-s3` on Windows? If yes, did you need to do some adjustments to get the tool working?

**Comment by laurilehmijoki** [comment] 2013-03-15 05:27
I'm closing this issue because I cannot get a grasp on the actual problem. If you are able to give new hints on how to reproduce this problem, please re-open this issue.

**Closed as completed by laurilehmijoki** 2013-03-15 05:27 UTC
